### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by OmegleMan29** [ash47/OmegleMiddleMan#65] opened 2021-06-13 09:37 UTC
Is it working now or still not working?

**Comment by ncollens5** [comment] 2021-06-13 15:23
Nope, not working

**Comment by fm-123** [comment] 2021-06-16 12:42
I have an actual fix which I would be willing to share against payment in BTC.

**Comment by ncollens5** [comment] 2021-06-16 15:38
Oh Really? Then Post a screen shot while the app's working

**Comment by fm-123** [comment] 2021-06-16 22:12
I'm not entirely sure how to prove it (suggestions welcome) but here is a screenshot next to the Washington Post today.

<img width="1675" alt="Screenshot 2021-06-17 at 00 06 10" src="https://user-images.githubusercontent.com/86001466/122301190-a4658b80-cf00-11eb-8586-e0921435be60.png">

**Comment by fm-123** [comment] 2021-06-16 22:13
You can tell me some things to say to strangers. I'll copy and paste the text and film the conversation.

**Comment by ash47** [comment] 2021-06-17 01:05
I'll take a look at this later today, it's likely a simple fix, so I'll say
you the $$$, it likely won't take long to fix.

Feel free to make a pull request but I'm not going to pay you Bitcoin for a
fix I can do in probably 15 minutes.

**Comment by ash47** [comment] 2021-06-17 03:01
@OmegleMan29 I have fixed the issue, it should now connect, for the record, the dude wanted to charge you $$$ to add 2 characters to the code ",t" was missing:

![image](https://user-images.githubusercontent.com/3754510/122324455-24750b00-cf6c-11eb-904d-e35cf7efd601.png)

Please advise if the issue is not fixed, i will close this issue within a few days if you dont reply

**Comment by ash47** [comment] 2021-06-17 03:03
Deleted the dodgy comments, please comment if you have any other issues, as it should now be fixed. I am closing the issue.

**Closed by ash47** 2021-06-17 03:03 UTC
